name: Docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: catalogs
          environment-file: environment.yml
          mamba-version: "*"
          python-version: 3.10
          auto-activate-base: false
      - name: Install local package
        shell: bash -l {0}
        run: |
          python -m ipykernel install --user --name=catalogs
          make html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/html # The folder the action should deploy.