name: xdatasets
channels:
    - conda-forge
dependencies:
    - python >=3.9,<3.12
    - bottleneck
    - clisops
    - dask
    - geopandas
    - intake
    - intake-geopandas
    - intake-xarray >=0.6.1
    - ipython
    - jsonpickle
    - matplotlib-base
    - pint>=0.10
    - tqdm
    - xagg
    - xarray
    - zarr
