name: xdatasets
channels:
    - conda-forge
dependencies:
    - python >=3.9,<3.12
    - IPyKernel
    - bottleneck
    - cartopy
    - dask
    - furo
    - geopandas
    - geoviews
    - hvplot
    - intake
    - intake-geopandas
    - intake-xarray >=0.6.1
    - matplotlib
    - nbsphinx
    - netCDF4
    - rioxarray
    - s3fs
    - sphinx
    - tqdm
    - xarray
    - zarr
