name: xdatasets
channels:
    - conda-forge
dependencies:
    - python=3.9
    - IPyKernel
    - xarray
    - dask
    - netCDF4
    - bottleneck
    - s3fs
    - zarr
    - cartopy
    - geoviews
    - rioxarray
    - matplotlib
    - tqdm
    - intake
    - geopandas
    - clisops
    - hvplot
    - intake-xarray=0.6.1
    - intake-geopandas
    - xesmf
    - furo
    - nbsphinx
    - sphinx